# Generated by Django 6.0.7 on 2026-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messages_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
