# Generated by Django 6.0.7 on 2026-08-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_messages_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reset_time', models.TimeField(default='07:00', help_text="Every user's message count resets to 0 at this time, every day.")),
                ('last_reset_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
